services:
  - type: web
    name: wedding-website-qa
    env: node
    buildCommand: npm install && npm run render-build
    startCommand: npm run render-start
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: / 